### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by djromero** [samjwill/nvim-unception#4]
Problem 1: 
`nvim file1`, open terminal, run `nvim file2` 
Expected: file2 opened in a new buffer, file1 and terminal untouched
Actual: file1 and terminal goes away, file2 is the only buffer left

Problem 2:
After performing the steps in "Problem 1", quits nvim.
When trying to open it back `nvim file3` it does nothing.

Tested with my usual configuration, nothing weird, just LSP and some other "standard" plugins.

**Comment by samjwill** [comment]
Problem 1 is actually how I designed it, the terminal buffer that the new buffer replaces gets deleted so that you don't end up with a bunch of empty terminals, but now that you mention it, I do agree that the behavior might not be what's expected. I'll look at making the automatic buffer deletion optional. Thanks for the suggestion!

Problem 2 is odd. If you're able to reproduce it, and get it into a state where nvim isn't launching, would you be able to run `pgrep nvim -u $USER` and see if you're still receiving a PID as output? The way the plugin checks if it should send a command to the server and quit immediately, or launch and start the server instead is kind of dumb, and depends on the output of that command. Perhaps I can come up with something a bit smarter.

**Comment by samjwill** [comment]
I was able to remedy problem 1 for me locally by separating the :argedit call into :argadd and :argument calls. The change is now in main. Not 100% sure what the issue was to be honest... perhaps an issue with Neovim core where :argedit doesn't properly trigger if received from a client-server command? Seems to work for me now in any case.

Hopefully that works for you :)
