### ISSUE TITLE
add feature that after hitting `:q` from a file opened by nvim in a terminal you are brought back to the terminal

### ISSUE THREAD

**Issue by jam1015** [samjwill/nvim-unception#61]
say I am in a terminal and I open a file using this plugin.  and then I enter `:q`.  right now the window closes, whereas a nested neovim session would have brought me back to the terminal. you might add an option to be brought back to the terminal as if the sessions were nested.

**Comment by samjwill** [comment]
Thanks for the suggestion!

Unfortunately, I'm not 100% sure how I would handle this elegantly.

Would you envision there being an `autocmd` that would place the terminal in the window with focus prior to quitting a specific buffer? If so, if a user opens a buffer through unception via the terminal, navigates away from the buffer, and then quits, the terminal wouldn't show up, which I'd imagine isn't the desired behavior. Additionally, if a user loads a buffer in another window in a separate tab, and then quits the buffer, the terminal would be moved over there, which might be fine, but it is a bit odd. If the terminal is still visible in another window, would it still take the unloaded buffer's place?

Maybe some sort of list of window and tab IDs associated with terminal buffer IDs would need to be maintained, but I can foresee that getting somewhat complex too (e.g. when a window is split), and I'm not sure that I currently have the time to implement such a mechanism in a robust manner. In theory, it wouldn't be much different from the way that the unceptioned git commit buffer currently works, but that approach is honestly somewhat naive and relies on the assumption that there's only ever one git commit buffer that's being edited at a time.

What I can do is offer an alternative that might suit your needs, which is also how I personally handle this. I have another plugin called [vim-bufdir](https://github.com/samjwill/vim-bufdir), which I install. I then create [a keymap](https://github.com/samjwill/dotfiles/blob/0064cc9bf2bfed86c8d99cd9963fcf885bed2fbd/.config/nvim/lua/keymaps.lua#L70) to open a terminal buffer in the directory of the file under the cursor. I also have [unception_delete_replaced_buffer](https://github.com/samjwill/nvim-unception/blob/2e475b74f3e581d21cd0ce86e0520546ac756791/doc/nvim-unception.txt#L28) set to true so that I don't have a ton of hidden terminal buffers just sitting there.

It's worth noting that this won't restore your bash history unless you update your .bashrc to sync it between terminals.

**Comment by samjwill** [comment]
Alternatively, you could run a `:vs` on the terminal buffer prior to opening the new file with `nvim my_filename.txt` so that the terminal buffer continues to be visible, or use `Ctrl-^` to jump back to the terminal buffer after writing instead of executing `:q`.

**Comment by yimyom** [comment]
a 3rd alternative would be to open a split window over or under the terminal buffer. For example, I often split my vi window in 2 columns. Let's say in the right column I have a few splits, one of them being a terminal.
What I'd love to do is open from the terminal a file and a new split is created in this  column, so that my terminal buffer is not closed. Basically your solution above, but done automatically, maybe with a config option to choose if one wants a vertical or horizontal split.

**Comment by samjwill** [comment]
@yimyom I like this idea. In hindsight, I probably should have made an enum for opening new buffers instead of booleans like  `g:unception_open_buffer_in_new_tab` so that it would be seamless to implement without messing up anyone's existing settings.

I _could_ add another boolean setting to enable vertical or horizontal splits, but I think the following is a more maintainable approach. There exists a User event that you can hook into which will trigger when a request to edit a file is received (see `:help UnceptionEditRequestReceived`). What you can do is add an autocmd that hooks into it and splits before opening a new buffer (assuming `g:unception_open_buffer_in_new_tab` is still set to false).

Something like this should work:

```
vim.api.nvim_create_autocmd(
    "User",
    {
        pattern = "UnceptionEditRequestReceived",
        callback = function()
            vim.cmd.vsplit()
        end
    }
)
```
